export const GET_INTERVENTIONS_REQUESTED = 'GET_INTERVENTIONS_REQUESTED';
export const GET_INTERVENTIONS_SUCCESSED = 'GET_INTERVENTIONS_SUCCESSED';
export const GET_INTERVENTIONS_FAILED = 'GET_INTERVENTIONS_FAILED';
export const ORDER_BY_DATE = 'ORDER_BY_DATE';
export const ADD_INTERVENTION = 'ADD_INTERVENTION';